covid-19/Controllers/WebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using covid_19.Models;
using covid_19.Data.DTOs;
using System.Net.Http;
using Newtonsoft.Json;
using covid_19.Infrastructure;
using covid_19.Data;

namespace covid_19.Controllers
{
    public class WebController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WebController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            var all = new allDTO();

            all = Infrastructure.Heraku.GetAllDTOFromHeraku("");

            if (all != null)
                return View(nameof(Index), all);

            return View();
        }

        public async Task<IActionResult> Save(int cases, int deaths, int recovered, DateTime timestamp)
        {
            var allDTO = new allDTO();

            allDTO.cases = cases;
            allDTO.deaths = deaths;
            allDTO.recovered = recovered;

            //all = Infrastructure.Heraku.GetAllDTOFromHeraku("");

            if (allDTO != null)
            {
                var all = new All(allDTO);
                all.Date = timestamp;

                _context.Add(all);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "AllMVC");
                //return View(nameof(Index), allDTO);
            }

            return View();
        }

        public async Task<IActionResult> Countries()
        {
            List<countryDTO> countries = new List<countryDTO>();
            countries = covid_19.Infrastructure.Heraku.GetCountryFromHeraku("");

            IEnumerable<countryDTO> sorted = new List<countryDTO>();
            countries.RemoveAll(t => t.country == "Total:");


            if (countries != null)
                return View(countries.OrderByDescending(c => c.cases).ToList());

            throw new NotImplementedException();
        }

        public async Task<IActionResult> SaveCountries(DateTime timestamp, IEnumerable<countryDTO> countries)
        {
            if (countries.Count() == 0)
                countries = covid_19.Infrastructure.Heraku.GetCountryFromHeraku("");

            if (timestamp == DateTime.MinValue)
                timestamp = DateTime.Now;

            foreach(var item in countries)
            {
                var country = new Country(item);
                country.Date = timestamp;
                _context.Add(country);
            }

                await _context.SaveChangesAsync();

            return RedirectToAction("Index", "CountriesMVC");
            //return View( ( nameof(Countries), countries.OrderByDescending(c => c.cases).ToList());
        }
    }
}

covid-19/Controllers/api/AllController.cs
using covid_19.Data;
using covid_19.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace covid_19.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AllController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public AllController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/All
        [HttpGet]
        public async Task<ActionResult<IEnumerable<All>>> GetAll()
        {
            return await _context.All.ToListAsync();
        }

        //public static async void GetAllFromHeraku(string endpoint)
        //{
        //    //Define your baseUrl
        //    string baseUrl = "https://coronavirus-19-api.herokuapp.com/";
        //    //Have your using statements within a try/catch blokc that will catch any exceptions.
        //    try
        //    {
        //        //HttpClient client_veni = new HttpClient();
        //        //We will now define your HttpClient with your first using statement which will use a IDisposable.
        //        using (HttpClient client = new HttpClient())
        //        {
        //            //In the next using statement you will initiate the Get Request, use the await keyword so it will execute the using statement in order.
        //            //The HttpResponseMessage which contains status code, and data from response.
        //            using (HttpResponseMessage res = await client.GetAsync(baseUrl + endpoint))
        //            {
        //                //Then get the data or content from the response in the next using statement, then within it you will get the data, and convert it to a c# object.
        //                using (HttpContent content = res.Content)
        //                {
        //                    //Now assign your content to your data variable, by converting into a string using the await keyword.
        //                    var data = await content.ReadAsStringAsync();
        //                    //If the data isn't null return log convert the data using newtonsoft JObject Parse class method on the data.
        //                    if (data != null)
        //                    {
        //                        //Now log your data in the console
        //                        Console.WriteLine("data------------{0}", data);

        //                    }
        //                    else
        //                    {
        //                        Console.WriteLine("NO Data----------");
        //                    }

        //                }
        //            }
        //        }
        //    }
        //    catch (Exception exception)
        //    {
        //        Console.WriteLine("Exception Hit------------");
        //        Console.WriteLine(exception);
        //    }
        //}

        // GET: api/All/5
        [HttpGet("{id}")]
        public async Task<ActionResult<All>> GetAll(int id)
        {
            var all = await _context.All.FindAsync(id);

            if (all == null)
            {
                return NotFound();
            }

            return all;
        }

        // PUT: api/All/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutAll(int id, All all)
        {
            if (id != all.Id)
            {
                return BadRequest();
            }

            _context.Entry(all).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AllExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/All
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        [HttpPost]
        public async Task<ActionResult<All>> PostAll()
        {

            allDTO allDTO = new allDTO();
            allDTO = covid_19.Infrastructure.Heraku.GetAllDTOFromHeraku("");
            
            All all = new All(allDTO);

            if (all != null )

            _context.All.Add(all);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetAll", new { id = all.Id }, all);
        }

        // DELETE: api/All/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<All>> DeleteAll(int id)
        {
            var all = await _context.All.FindAsync(id);
            if (all == null)
            {
                return NotFound();
            }

            _context.All.Remove(all);
            await _context.SaveChangesAsync();

            return all;
        }

        private All GetAllFromHeraku(string BaseAddress)
        {
            All all = new All();
            //Martin: this will overuse the server's resources
            HttpClient client = new HttpClient();

            //HTTP GET
            if(BaseAddress == "")
                client.BaseAddress = new Uri("https://coronavirus-19-api.herokuapp.com/");

            var responseTask = client.GetAsync("all");
            responseTask.Wait();


            var content = responseTask.Result.Content.ReadAsStringAsync().Result;

            if (responseTask.Result.IsSuccessStatusCode)
            {
                allDTO alls = JsonConvert.DeserializeObject<allDTO>(content);

                all.Cases = alls.cases;
                all.Deaths = alls.deaths;
                all.Recovered = alls.recovered;
                all.Date = DateTime.Now;

                return all;
            }
            else //web api sent error response 
            {
                //log response status here..
                return all;
            }
        }
        private bool AllExists(int id)
        {
            return _context.All.Any(e => e.Id == id);
        }
    }
}

covid-19/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - covid_19</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">covid_19</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Web" asp-action="Index">Web All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Web" asp-action="Countries">Web Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AllMVC" asp-action="Index">All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CountriesMVC" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="All" asp-action="PostAll" method="get">GetAll</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="PostCountry" method="get">GetCountries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - covid_19 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>