covid-19/Controllers/CountriesMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using covid_19.Data;
using covid_19.Models;
using ClosedXML.Excel;
using System.Text;
using System.IO;
using Microsoft.EntityFrameworkCore.Internal;

namespace covid_19.Controllers
{
    public class CountriesMVCController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CountriesMVCController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Countries
        public async Task<IActionResult> Index(string searchString, string sortOrder, string currentFilter)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.GenreSortParam = sortOrder == "Genre" ? "genre_desc" : "Genre";
            ViewBag.ItemsSortParam = sortOrder == "Items" ? "items_desc" : "Items";
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearch = searchString;
            
            if(!String.IsNullOrEmpty(currentFilter))
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;
            var maxDate = (from q in _context.Countries select q.Date).Max();

            var countries = await _context.Countries
                                          .Where(d => d.Date == maxDate)
                                          .OrderByDescending(c => c.Date)
                                          .ThenByDescending(x => x.Cases)
                                          .ToListAsync();

            var datesRange = countries.Select(d => d.Date)
                                      .Distinct()
                                      .OrderByDescending(d => d.Date)
                                      .ToList();

            if (!String.IsNullOrEmpty(searchString))
                countries = countries.Where(c => c.Name.Contains(searchString)).ToList();
            else
                countries = countries.Where(c => c.Date == datesRange.Max()).ToList();

            return View(countries);
        }

        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            var list = await _context.Countries
                                     .Where(c => c.Name == country.Name)
                                     .OrderByDescending(d => d.Date)
                                     .ToListAsync();

            var countryViemModel = new covid_19.ViewModels.CountryViewModel(country, list);

            return View(countryViemModel);
        }

        // GET: Countries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Cases,TodayCases,Deaths,TodayDeaths,Recovered,Active,Critical,Date")] Country country)
        {
            if (ModelState.IsValid)
            {
                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Cases,TodayCases,Deaths,TodayDeaths,Recovered,Active,Critical,Date")] Country country)
        {
            if (id != country.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var country = await _context.Countries.FindAsync(id);
            _context.Countries.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: AllMVC/Csv
        public async Task<IActionResult> Csv()
        {
            var builder = new StringBuilder();
            builder.AppendLine("Id,Name,Date,Cases,Recovered,Deaths,TodayCases,TodayDeaths,Active,Critical,Country,Tests per 1M, Total test, Cases per 1M, Deaths per 1M");

            var countries = await _context.Countries.ToListAsync();

            foreach (var item in countries)
            {
                builder.AppendLine($"{item.Id}" +
                                   $",{item.Name}" +
                                   $",{item.Date}" +
                                   $",{item.Cases}" +
                                   $",{item.Recovered}" +
                                   $",{item.Deaths}" +
                                   $",{item.TodayCases}" +
                                   $",{item.TodayDeaths}" +
                                   $",{item.Active}" +
                                   $",{item.Critical}" +
                                   $",{item.Name}," +
                                   $"{item.testsPerOneMillion}," +
                                   $"{item.totalTests}," +
                                   $"{item.casesPerOneMillion}," +
                                   $"{item.deathsPerOneMillion}");
            }

            return File(Encoding.UTF8.GetBytes(builder.ToString())
                                , "text/csv"
                                , "countries-"+ DateTime.Now.ToString("yyyy-MM-dd HHmmss") +".csv");
        }

        // GET: AllMVC/Excel
        public async Task<IActionResult> Excel()
        {
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Countries");
                var currentRow = 1;
                worksheet.Cell(currentRow, 1).Value = "Id";
                worksheet.Cell(currentRow, 2).Value = "Date";
                worksheet.Cell(currentRow, 3).Value = "Cases";
                worksheet.Cell(currentRow, 4).Value = "Recovered";
                worksheet.Cell(currentRow, 5).Value = "Deaths";
                worksheet.Cell(currentRow, 6).Value = "TodayCases";
                worksheet.Cell(currentRow, 7).Value = "TodayDeaths";
                worksheet.Cell(currentRow, 8).Value = "Active";
                worksheet.Cell(currentRow, 9).Value = "Critical";
                worksheet.Cell(currentRow, 10).Value = "Country";
                worksheet.Cell(currentRow, 11).Value = "Tests per 1M"; 
                worksheet.Cell(currentRow, 12).Value = "Total test"; 
                worksheet.Cell(currentRow, 13).Value = "Cases per 1M"; 
                worksheet.Cell(currentRow, 14).Value = "Deaths per 1M"; 

                var countries = await _context.Countries.ToListAsync();

                foreach (var item in countries)
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 1).Value = item.Id;
                    worksheet.Cell(currentRow, 2).Value = item.Date;
                    worksheet.Cell(currentRow, 3).Value = item.Cases;
                    worksheet.Cell(currentRow, 4).Value = item.Recovered;
                    worksheet.Cell(currentRow, 5).Value = item.Deaths;
                    worksheet.Cell(currentRow, 6).Value = item.TodayCases;
                    worksheet.Cell(currentRow, 7).Value = item.TodayDeaths;
                    worksheet.Cell(currentRow, 8).Value = item.Active;
                    worksheet.Cell(currentRow, 9).Value = item.Critical;
                    worksheet.Cell(currentRow, 10).Value = item.Name;

covid-19/Views/CountriesMVC/Create.cshtml
@model covid_19.Models.Country

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cases" class="control-label"></label>
                <input asp-for="Cases" class="form-control" />
                <span asp-validation-for="Cases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TodayCases" class="control-label"></label>
                <input asp-for="TodayCases" class="form-control" />
                <span asp-validation-for="TodayCases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deaths" class="control-label"></label>
                <input asp-for="Deaths" class="form-control" />
                <span asp-validation-for="Deaths" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TodayDeaths" class="control-label"></label>
                <input asp-for="TodayDeaths" class="form-control" />
                <span asp-validation-for="TodayDeaths" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recovered" class="control-label"></label>
                <input asp-for="Recovered" class="form-control" />
                <span asp-validation-for="Recovered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Critical" class="control-label"></label>
                <input asp-for="Critical" class="form-control" />
                <span asp-validation-for="Critical" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

covid-19/Views/CountriesMVC/Delete.cshtml
@model covid_19.Models.Country

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cases)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cases)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TodayCases)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TodayCases)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deaths)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deaths)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TodayDeaths)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TodayDeaths)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recovered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recovered)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Critical)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Critical)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

covid-19/Views/CountriesMVC/Details.cshtml
@model covid_19.ViewModels.CountryViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cases)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cases)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TodayCases)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TodayCases)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deaths)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Deaths)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TodayDeaths)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TodayDeaths)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Recovered)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Recovered)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Critical)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Critical)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>

@if (Model.countries.Count > 0)
{
    <div>
        <hr />
        <h4>Records for @Model.Name</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cases)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TodayCases)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Deaths)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TodayDeaths)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Recovered)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Active)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Critical)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.casesPerOneMillion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.deathsPerOneMillion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.testsPerOneMillion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.totalTests)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.countries)
                {
                    <tr>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date, "{yyyy-MM-dd}")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cases)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TodayCases)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Deaths)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TodayDeaths)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Recovered)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Active)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Critical)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.casesPerOneMillion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.deathsPerOneMillion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.testsPerOneMillion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.totalTests)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

covid-19/Views/CountriesMVC/Edit.cshtml
@model covid_19.Models.Country

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cases" class="control-label"></label>
                <input asp-for="Cases" class="form-control" />
                <span asp-validation-for="Cases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TodayCases" class="control-label"></label>
                <input asp-for="TodayCases" class="form-control" />
                <span asp-validation-for="TodayCases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deaths" class="control-label"></label>
                <input asp-for="Deaths" class="form-control" />
                <span asp-validation-for="Deaths" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TodayDeaths" class="control-label"></label>
                <input asp-for="TodayDeaths" class="form-control" />
                <span asp-validation-for="TodayDeaths" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recovered" class="control-label"></label>
                <input asp-for="Recovered" class="form-control" />
                <span asp-validation-for="Recovered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Critical" class="control-label"></label>
                <input asp-for="Critical" class="form-control" />
                <span asp-validation-for="Critical" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

covid-19/Views/CountriesMVC/Index.cshtml
@model IEnumerable<covid_19.Models.Country>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index of Coutry records</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Create New</a> |
    <a asp-action="Csv" class="btn btn-outline-info">Export to CSV</a> |
    <a asp-action="Excel" class="btn btn-outline-success">Export to Excel</a>
    @using (Html.BeginForm("Index", "CountriesMVC", FormMethod.Get))
    {
        <div class="form-inline">
            Country: @Html.TextBox("SearchString", null, new { @class = "form-control" })  
            <input class="btn btn-info" type="submit" value="Filter" />
        <p></p>
        </div>
    }
    </p>


    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cases)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TodayCases)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Deaths)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TodayDeaths)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Recovered)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Active)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Critical)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.casesPerOneMillion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.deathsPerOneMillion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.testsPerOneMillion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.totalTests)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cases)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TodayCases)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Deaths)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TodayDeaths)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Recovered)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Critical)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.casesPerOneMillion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.deathsPerOneMillion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.testsPerOneMillion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.totalTests)
                    </td>
                </tr>
            }
        </tbody>
    </table>