covid-19/Controllers/AllMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using covid_19.Data;
using covid_19.Models;
using System.Text;
using ClosedXML.Excel;
using System.IO;
using covid_19.Data.Migrations;
using ClosedXML;

namespace covid_19.Controllers
{
    public class AllMVCController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AllMVCController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AllMVC
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewBag.DateSortParm = sortOrder == "asc" ? "date_desc" : "asc";
            ViewBag.CasesSortParam = sortOrder == "cases_asc" ? "cases_desc" : "cases_asc";
            ViewBag.DeathsSortParam = sortOrder == "deaths_asc" ? "deaths_desc" : "deaths_asc";
            ViewBag.RecoveredSortParam = sortOrder == "recovered_asc" ? "recovered_desc" : "recovered_asc";
            ViewBag.CurrentSort = sortOrder;

            //var filter = from record in _context.All
            //             group record by new
            //             {
            //                 record.Date.Year,
            //                 record.Date.Month,
            //                 record.Date.Day,
            //             }
            //                into g
            //             select new
            //             {
            //                  Date = g.Max(c => c.Date)
            //             };
            //var distinctDates = await filter.ToListAsync();

            //var allDistinct = await (from record in _context.All
            //                         where distinctDates.Contains(new { record.Date })
            //                         select record).ToListAsync();
            //var allDistinct = _context.All
            //                                .Where(x => distinctDates.Contains(new { x.Date }))
            //                                .Tolist();

            //var all = await _context.All.ToListAsync();
            var all = await _context.All.FromSqlRaw("SELECT* FROM[All]" +
                                                    "WHERE [Date] in " +
                                                            "(SELECT TOP(1000) Max([Date])" +
                                                                    "FROM[All]" +
                                                                    "GROUP BY YEAR([Date])," +
                                                                    "Month([Date])," +
                                                                    "Day([Date]))"
                                                    ).ToListAsync();

            switch (sortOrder)
            {
                case "asc":
                    all = all.OrderBy(a => a.Date).ToList();
                    break;
                case "cases_asc":
                    all = all.OrderBy(a => a.Cases).ToList();
                    break;
                case "cases_desc":
                    all = all.OrderByDescending(a => a.Cases).ToList();
                    break;
                case "deaths_asc":
                    all = all.OrderBy(a => a.Deaths).ToList();
                    break;
                case "deaths_desc":
                    all = all.OrderByDescending(a => a.Deaths).ToList();
                    break;
                case "recovered_asc":
                    all = all.OrderBy(a => a.Recovered).ToList();
                    break;
                case "recovered_desc":
                    all = all.OrderByDescending(a => a.Recovered).ToList();
                    break;
                default:
                    all = all.OrderByDescending(a => a.Date).ToList();
                    break;
            }
            return View(all);
        }

        // GET: AllMVC
        public async Task<IActionResult> List(string sortOrder)
        {
            ViewBag.DateSortParm = sortOrder == "asc" ? "date_desc" : "asc";
            ViewBag.CasesSortParam = sortOrder == "cases_asc" ? "cases_desc" : "cases_asc";
            ViewBag.DeathsSortParam = sortOrder == "deaths_asc" ? "deaths_desc" : "deaths_asc";
            ViewBag.RecoveredSortParam = sortOrder == "recovered_asc" ? "recovered_desc" : "recovered_asc";
            ViewBag.CurrentSort = sortOrder;

            var all = await _context.All.ToListAsync();

            switch (sortOrder)
            {
                case "asc":
                    all = all.OrderBy(a => a.Date).ToList();
                    break;
                case "cases_asc":
                    all = all.OrderBy(a => a.Cases).ToList();
                    break;
                case "cases_desc":
                    all = all.OrderByDescending(a => a.Cases).ToList();
                    break;
                case "deaths_asc":
                    all = all.OrderBy(a => a.Deaths).ToList();
                    break;
                case "deaths_desc":
                    all = all.OrderByDescending(a => a.Deaths).ToList();
                    break;
                case "recovered_asc":
                    all = all.OrderBy(a => a.Recovered).ToList();
                    break;
                case "recovered_desc":
                    all = all.OrderByDescending(a => a.Recovered).ToList();
                    break;
                default:
                    all = all.OrderByDescending(a => a.Date).ToList();
                    break;
            }
            return View(all);
        }

        // GET: Load
        public async Task<IActionResult> Load()
        {
            var allDTO = covid_19.Infrastructure.Heraku.GetAllDTOFromHeraku("");
            var all = new All(allDTO)
            { 
                Date = DateTime.Now 
            };

            _context.Add(all);
            await _context.SaveChangesAsync();

            return View("Index", await _context.All.OrderByDescending(a => a.Date).ToListAsync());
        }

        // GET: AllMVC/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var all = await _context.All
                .FirstOrDefaultAsync(m => m.Id == id);
            if (all == null)
            {
                return NotFound();
            }

            return View(all);
        }

        // GET: AllMVC/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AllMVC/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Cases,Deaths,Recovered")] All all)
        {
            if (ModelState.IsValid)
            {
                _context.Add(all);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(all);
        }

        // GET: AllMVC/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var all = await _context.All.FindAsync(id);
            if (all == null)
            {
                return NotFound();
            }
            return View(all);
        }

        // POST: AllMVC/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Cases,Deaths,Recovered")] All all)
        {
            if (id != all.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(all);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AllExists(all.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(all);
        }

        // GET: AllMVC/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var all = await _context.All
                .FirstOrDefaultAsync(m => m.Id == id);
            if (all == null)
            {
                return NotFound();
            }

            return View(all);
        }

        // POST: AllMVC/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var all = await _context.All.FindAsync(id);
            _context.All.Remove(all);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: AllMVC/Csv
        public async Task<IActionResult> Csv()
        {
            var builder = new StringBuilder();
            builder.AppendLine("Id,Date,Cases,Recovered,Deaths");

            var all = await _context.All.ToListAsync();

            foreach (var item in all)
            {

covid-19/Views/AllMVC/Create.cshtml
@model covid_19.Models.All

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>All</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cases" class="control-label"></label>
                <input asp-for="Cases" class="form-control" />
                <span asp-validation-for="Cases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deaths" class="control-label"></label>
                <input asp-for="Deaths" class="form-control" />
                <span asp-validation-for="Deaths" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recovered" class="control-label"></label>
                <input asp-for="Recovered" class="form-control" />
                <span asp-validation-for="Recovered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

covid-19/Views/AllMVC/Delete.cshtml
@model covid_19.Models.All

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>All</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cases)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cases)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deaths)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deaths)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recovered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recovered)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

covid-19/Views/AllMVC/Details.cshtml
@model covid_19.Models.All

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>All</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cases)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cases)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deaths)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Deaths)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Recovered)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Recovered)
        </dd>
        @*Bad practice*@
        <dt class="col-sm-2">
            Remaining
        </dt>
        <dd class="col-sm-10">
            @Html.Label((Model.Cases - Model.Deaths - Model.Recovered).ToString())
        </dd>
        <dt class="col-sm-2">
            Remaining %
        </dt>
        <dd class="col-sm-10">
            @Html.Label(Model.GetRemainingPercent().ToString())
        </dd>
        <dt class="col-sm-2">
            Recovered %
        </dt>
        <dd class="col-sm-10">
            @Html.Label(Model.GetRecoveredPercent().ToString())
        </dd>
        <dt class="col-sm-2">
            Death %
        </dt>
        <dd class="col-sm-10">
            @Html.Label(Model.GetDeathPercent().ToString())
        </dd>
        <dt class="col-sm-2">
            Recovered to Death
        </dt>
        <dd class="col-sm-10">
            @Html.Label(Model.GetRecoveredToDeath().ToString())
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

covid-19/Views/AllMVC/Edit.cshtml
@model covid_19.Models.All

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>All</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cases" class="control-label"></label>
                <input asp-for="Cases" class="form-control" />
                <span asp-validation-for="Cases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deaths" class="control-label"></label>
                <input asp-for="Deaths" class="form-control" />
                <span asp-validation-for="Deaths" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recovered" class="control-label"></label>
                <input asp-for="Recovered" class="form-control" />
                <span asp-validation-for="Recovered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

covid-19/Views/AllMVC/Index.cshtml
@model IEnumerable<covid_19.Models.All>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Create New</a> | 
    <a asp-action="Load" class="btn btn-outline-secondary">Load</a> | 
    <a asp-action="Csv" class="btn btn-outline-info">Export to CSV</a> |
    <a asp-action="Excel" class="btn btn-outline-success">Export to Excel</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.Date),"Index", "AllMVC", new { sortOrder= ViewBag.DateSortParm })
            </th>
            <th>
                @Html.ActionLink( @Html.DisplayNameFor(model => model.Cases), "Index", "AllMVC", new { sortOrder = ViewBag.CasesSortParam})
            </th>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.Deaths), "Index", "AllMVC", new { sortOrder = ViewBag.DeathsSortParam })
            </th>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.Recovered), "Index", "AllMVC", new { sortOrder = ViewBag.RecoveredSortParam })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date,"yyyy-MM-dd HH:mm:ss")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cases)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deaths)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recovered)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

covid-19/Views/AllMVC/List.cshtml
@model IEnumerable<covid_19.Models.All>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Create New</a> |
    <a asp-action="Load" class="btn btn-outline-secondary">Load</a> |
    <a asp-action="Csv" class="btn btn-outline-info">Export to CSV</a> |
    <a asp-action="Excel" class="btn btn-outline-success">Export to Excel</a> |
    <a asp-action="Index" class="btn btn-outline-info">List</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.Date),"Index", "AllMVC", new { sortOrder= ViewBag.DateSortParm })
            </th>
            <th>
                @Html.ActionLink( @Html.DisplayNameFor(model => model.Cases), "Index", "AllMVC", new { sortOrder = ViewBag.CasesSortParam})
            </th>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.Deaths), "Index", "AllMVC", new { sortOrder = ViewBag.DeathsSortParam })
            </th>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.Recovered), "Index", "AllMVC", new { sortOrder = ViewBag.RecoveredSortParam })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date,"yyyy-MM-dd HH:mm:ss")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cases)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deaths)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recovered)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>